# Generated by Django 6.0.3 on 2026-03-19 18:57

import django.core.files.storage
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django_afip.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVatCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='code')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
                ('cmp_clase', models.CharField(help_text='The class of the client VAT condition.', max_length=10, verbose_name='cmp clase')),
            ],
            options={
                'verbose_name': 'client VAT condition',
                'verbose_name_plural': 'client VAT conditions',
            },
        ),
        migrations.CreateModel(
            name='ConceptType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='code')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='valid from')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='valid until')),
            ],
            options={
                'verbose_name': 'concept type',
                'verbose_name_plural': 'concept types',
            },
        ),
        migrations.CreateModel(
            name='CurrencyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='code')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='valid from')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='valid until')),
            ],
            options={
                'verbose_name': 'currency type',
                'verbose_name_plural': 'currency types',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='code')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='valid from')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='valid until')),
            ],
            options={
                'verbose_name': 'document type',
                'verbose_name_plural': 'document types',
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(verbose_name='code')),
                ('message', models.CharField(max_length=255, verbose_name='message')),
            ],
            options={
                'verbose_name': 'observation',
                'verbose_name_plural': 'observations',
            },
        ),
        migrations.CreateModel(
            name='OptionalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='valid from')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='valid until')),
                ('code', models.CharField(max_length=4, verbose_name='code')),
            ],
            options={
                'verbose_name': 'optional type',
                'verbose_name_plural': 'optional types',
            },
        ),
        migrations.CreateModel(
            name='PointOfSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='number')),
                ('issuance_type', models.CharField(help_text='Indicates if this POS emits using CAE and CAEA.', max_length=200, verbose_name='issuance type')),
                ('blocked', models.BooleanField(default=False, verbose_name='blocked')),
                ('drop_date', models.DateField(blank=True, null=True, verbose_name='drop date')),
                ('issuing_name', models.CharField(blank=True, default='', help_text='The name of the issuing entity as shown on receipts.', max_length=128, verbose_name='issuing name')),
                ('issuing_address', models.TextField(blank=True, default='', help_text='The address of the issuing entity as shown on receipts.', verbose_name='issuing address')),
                ('issuing_email', models.CharField(blank=True, default='', help_text='The email of the issuing entity as shown on receipts.', max_length=128, verbose_name='issuing email')),
                ('vat_condition', models.CharField(blank=True, choices=[('IVA Responsable Inscripto', 'IVA Responsable Inscripto'), ('IVA Responsable No Inscripto', 'IVA Responsable No Inscripto'), ('IVA Exento', 'IVA Exento'), ('No Responsable IVA', 'No Responsable IVA'), ('Responsable Monotributo', 'Responsable Monotributo')], default='', max_length=48, verbose_name='vat condition')),
                ('gross_income_condition', models.CharField(blank=True, default='', max_length=48, verbose_name='gross income condition')),
                ('sales_terms', models.CharField(blank=True, default='', help_text='The terms of the sale printed onto receipts by default (eg: single payment, checking account, etc).', max_length=48, verbose_name='sales terms')),
            ],
            options={
                'verbose_name': 'point of sales',
                'verbose_name_plural': 'points of sales',
            },
        ),
        migrations.CreateModel(
            name='ReceiptType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='code')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='valid from')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='valid until')),
            ],
            options={
                'verbose_name': 'receipt type',
                'verbose_name_plural': 'receipt types',
            },
        ),
        migrations.CreateModel(
            name='TaxPayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A friendly name to recognize this taxpayer.', max_length=32, verbose_name='name')),
                ('key', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='afip/taxpayers/keys/', verbose_name='key')),
                ('certificate', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='afip/taxpayers/certs/', verbose_name='certificate')),
                ('cuit', models.BigIntegerField(verbose_name='cuit')),
                ('is_sandboxed', models.BooleanField(help_text='Indicates if this taxpayer should use with the sandbox servers rather than the production servers.', verbose_name='is sandboxed')),
                ('certificate_expiration', models.DateTimeField(editable=False, help_text='Stores expiration for the current certificate.<br>Note that this field is updated pre-save, so the value may be invalid for unsaved models.', null=True, verbose_name='certificate expiration')),
                ('active_since', models.DateField(help_text='Date since which this taxpayer has been legally active.', verbose_name='active since')),
                ('logo', models.ImageField(blank=True, help_text='A logo to use when generating printable receipts.', null=True, upload_to='afip/taxpayers/logos/', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'taxpayer',
                'verbose_name_plural': 'taxpayers',
            },
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='code')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='valid from')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='valid until')),
            ],
            options={
                'verbose_name': 'tax type',
                'verbose_name_plural': 'tax types',
            },
        ),
        migrations.CreateModel(
            name='VatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='code')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='valid from')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='valid until')),
            ],
            options={
                'verbose_name': 'vat type',
                'verbose_name_plural': 'vat types',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.BigIntegerField(help_text='The document number of the recipient of this receipt.', verbose_name='document number')),
                ('receipt_number', models.PositiveIntegerField(blank=True, help_text='If left blank, the next valid number will assigned when validating the receipt.', null=True, verbose_name='receipt number')),
                ('issued_date', models.DateField(help_text='Can diverge up to 5 days for good, or 10 days otherwise.', verbose_name='issued date')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Must be equal to the sum of net_taxed, exempt_amount, net_taxes, and all taxes and vats.', max_digits=15, verbose_name='total amount')),
                ('net_untaxed', models.DecimalField(decimal_places=2, help_text='The total amount to which taxes do not apply.<br>For C-type receipts, this must be zero.', max_digits=15, verbose_name='total untaxable amount')),
                ('net_taxed', models.DecimalField(decimal_places=2, help_text='The total amount to which taxes apply.<br>For C-type receipts, this is equal to the subtotal.', max_digits=15, verbose_name='total taxable amount')),
                ('exempt_amount', models.DecimalField(decimal_places=2, help_text='Only for categories which are tax-exempt.<br>For C-type receipts, this must be zero.', max_digits=15, verbose_name='exempt amount')),
                ('service_start', models.DateField(blank=True, help_text='Date on which a service started. No applicable for goods.', null=True, verbose_name='service start date')),
                ('service_end', models.DateField(blank=True, help_text='Date on which a service ended. No applicable for goods.', null=True, verbose_name='service end date')),
                ('expiration_date', models.DateField(blank=True, help_text='Date on which this receipt expires. No applicable for goods.', null=True, verbose_name='receipt expiration date')),
                ('currency_quote', models.DecimalField(decimal_places=6, default=1, help_text="The currency's quote on the day this receipt was issued.", max_digits=10, verbose_name='currency quote')),
                ('client_vat_condition', models.ForeignKey(blank=True, help_text='The client VAT condition of the recipient of this receipt.', null=True, on_delete=django.db.models.deletion.PROTECT, to='afip.clientvatcondition', verbose_name='client VAT condition')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='afip.concepttype', verbose_name='concept')),
                ('currency', models.ForeignKey(default=django_afip.models.first_currency, help_text='Currency in which this receipt is issued.', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='afip.currencytype', verbose_name='currency')),
                ('document_type', models.ForeignKey(help_text='The document type of the recipient of this receipt.', on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='afip.documenttype', verbose_name='document type')),
                ('point_of_sales', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='afip.pointofsales', verbose_name='point of sales')),
                ('related_receipts', models.ManyToManyField(blank=True, to='afip.receipt', verbose_name='related receipts')),
                ('receipt_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='afip.receipttype', verbose_name='receipt type')),
            ],
            options={
                'verbose_name': 'receipt',
                'verbose_name_plural': 'receipts',
                'ordering': ('issued_date',),
                'unique_together': {('point_of_sales', 'receipt_type', 'receipt_number')},
            },
        ),
        migrations.CreateModel(
            name='Optional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250, verbose_name='optional value')),
                ('optional_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='afip.optionaltype', verbose_name='optional type')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='optionals', to='afip.receipt')),
            ],
            options={
                'verbose_name': 'optional',
                'verbose_name_plural': 'optionals',
            },
        ),
        migrations.CreateModel(
            name='ReceiptPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, help_text='The actual file which contains the PDF data.', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=django_afip.models._receipt_pdf_upload_to, verbose_name='pdf file')),
                ('issuing_name', models.CharField(max_length=128, verbose_name='issuing name')),
                ('issuing_address', models.TextField(verbose_name='issuing address')),
                ('issuing_email', models.CharField(blank=True, default='', max_length=128, verbose_name='issuing email')),
                ('vat_condition', models.CharField(choices=[('IVA Responsable Inscripto', 'IVA Responsable Inscripto'), ('IVA Responsable No Inscripto', 'IVA Responsable No Inscripto'), ('IVA Exento', 'IVA Exento'), ('No Responsable IVA', 'No Responsable IVA'), ('Responsable Monotributo', 'Responsable Monotributo')], max_length=48, verbose_name='vat condition')),
                ('gross_income_condition', models.CharField(max_length=48, verbose_name='gross income condition')),
                ('client_name', models.CharField(max_length=128, verbose_name='client name')),
                ('client_address', models.TextField(blank=True, verbose_name='client address')),
                ('client_vat_condition', models.CharField(choices=[('IVA Responsable Inscripto', 'IVA Responsable Inscripto'), ('IVA Responsable No Inscripto', 'IVA Responsable No Inscripto'), ('IVA Sujeto Exento', 'IVA Sujeto Exento'), ('Consumidor Final', 'Consumidor Final'), ('Responsable Monotributo', 'Responsable Monotributo'), ('Proveedor del Exterior', 'Proveedor del Exterior'), ('Cliente del Exterior', 'Cliente del Exterior'), ('IVA Liberado - Ley Nº 19.640', 'IVA Liberado - Ley Nº 19.640'), ('IVA Responsable Inscripto - Agente de Percepción', 'IVA Responsable Inscripto - Agente de Percepción'), ('Monotributista Social', 'Monotributista Social'), ('IVA no alcanzado', 'IVA no alcanzado')], max_length=48, verbose_name='client vat condition')),
                ('sales_terms', models.CharField(help_text='Should be something like "Cash", "Payable in 30 days", etc.', max_length=48, verbose_name='sales terms')),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='afip.receipt', verbose_name='receipt')),
            ],
            options={
                'verbose_name': 'receipt pdf',
                'verbose_name_plural': 'receipt pdfs',
            },
        ),
        migrations.CreateModel(
            name='ReceiptValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_date', models.DateTimeField(verbose_name='processed date')),
                ('cae', models.CharField(help_text='The CAE as returned by the AFIP.', max_length=14, verbose_name='cae')),
                ('cae_expiration', models.DateField(help_text='The CAE expiration as returned by the AFIP.', verbose_name='cae expiration')),
                ('observations', models.ManyToManyField(help_text='The observations as returned by the AFIP. These are generally present for failed validations.', related_name='validations', to='afip.observation', verbose_name='observations')),
                ('receipt', models.OneToOneField(help_text='The Receipt for which this validation applies.', on_delete=django.db.models.deletion.PROTECT, related_name='validation', to='afip.receipt', verbose_name='receipt')),
            ],
            options={
                'verbose_name': 'receipt validation',
                'verbose_name_plural': 'receipt validations',
            },
        ),
        migrations.AddField(
            model_name='pointofsales',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_of_sales', to='afip.taxpayer', verbose_name='owner'),
        ),
        migrations.CreateModel(
            name='AuthTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.IntegerField(default=django_afip.models.default_unique_id, verbose_name='unique id')),
                ('generated', models.DateTimeField(default=django_afip.models.default_generated, verbose_name='generated')),
                ('expires', models.DateTimeField(default=django_afip.models.default_expires, verbose_name='expires')),
                ('service', models.CharField(help_text='Service for which this ticket has been authorized.', max_length=34, verbose_name='service')),
                ('token', models.TextField(verbose_name='token')),
                ('signature', models.TextField(verbose_name='signature')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tickets', to='afip.taxpayer', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'authorization ticket',
                'verbose_name_plural': 'authorization tickets',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=80, verbose_name='description')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='base amount')),
                ('aliquot', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='aliquot')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='amount')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxes', to='afip.receipt')),
                ('tax_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='afip.taxtype', verbose_name='tax type')),
            ],
            options={
                'verbose_name': 'tax',
                'verbose_name_plural': 'taxes',
            },
        ),
        migrations.CreateModel(
            name='Vat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='base amount')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='amount')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vat', to='afip.receipt')),
                ('vat_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='afip.vattype', verbose_name='vat type')),
            ],
            options={
                'verbose_name': 'vat',
                'verbose_name_plural': 'vat',
            },
        ),
        migrations.AlterUniqueTogether(
            name='pointofsales',
            unique_together={('number', 'owner')},
        ),
        migrations.CreateModel(
            name='ReceiptEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128, verbose_name='description')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit before vat or taxes.', max_digits=15, verbose_name='unit price')),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text="Total net discount applied to row's total.", max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='discount')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='afip.receipt', verbose_name='receipt')),
                ('vat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_entries', to='afip.vattype', verbose_name='vat')),
            ],
            options={
                'verbose_name': 'receipt entry',
                'verbose_name_plural': 'receipt entries',
                'constraints': [models.CheckConstraint(condition=models.Q(('discount__gte', Decimal('0.0'))), name='discount_positive_value'), models.CheckConstraint(condition=models.Q(('discount__lte', django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('unit_price')))), name='discount_less_than_total')],
            },
        ),
    ]
