# Generated by Django 4.1.1 on 2022-09-06 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afip", "0011_caea"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caea",
            name="caea_code",
            field=models.BigIntegerField(
                help_text="CAEA code to operate offline AFIP",
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(regex="[0-9]{14}"),
                    django.core.validators.MinLengthValidator(14),
                    django.core.validators.MaxLengthValidator(14),
                ],
            ),
        ),
    ]
