# Generated by Django 5.1 on 2024-08-08 22:04
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afip', '0013_alter_receiptentry_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofsales',
            name='blocked',
            field=models.BooleanField(default=False, verbose_name='blocked'),
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='logo',
            field=models.ImageField(blank=True, help_text='A logo to use when generating printable receipts.', null=True, upload_to='afip/taxpayers/logos/', verbose_name='logo'),
        ),
    ]
