# Generated by Django 4.1.1 on 2022-09-06 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afip', '0013_alter_caea_caea_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caea',
            name='service',
        ),
    ]
