# Generated by Django 4.1.1 on 2022-09-06 21:43

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("afip", "0014_remove_caea_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caea",
            name="expires",
            field=models.DateField(verbose_name="expires"),
        ),
        migrations.AlterField(
            model_name="caea",
            name="final_date_inform",
            field=models.DateField(verbose_name="final_date_inform"),
        ),
        migrations.AlterField(
            model_name="caea",
            name="valid_since",
            field=models.DateField(verbose_name="valid_to"),
        ),
    ]
