# Generated by Django 4.1.1 on 2022-09-08 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afip', '0018_caeacounter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caeacounter',
            old_name='value',
            new_name='next_value',
        ),
    ]
