# Generated by Django 6.0.3 on 2026-04-07 18:33

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("afip", "0018_remove_receiptvalidation_result"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="receiptentry",
            options={
                "ordering": ("pk",),
                "verbose_name": "receipt entry",
                "verbose_name_plural": "receipt entries",
            },
        ),
    ]
