# Generated by Django 4.1.1 on 2022-09-13 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afip', '0019_rename_value_caeacounter_next_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='caea',
            field=models.ForeignKey(blank=True, help_text='CAEA in case that the receipt must contain it', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caea', to='afip.caea'),
        ),
    ]
