# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afip', '0020_backfill_receiptvalidation__processed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='receiptvalidation',
            name='validation',
        ),
        migrations.AlterField(
            model_name='receiptvalidation',
            name='processed_date',
            field=models.DateTimeField(verbose_name='processed date'),
        ),
        migrations.DeleteModel(
            name='Validation',
        ),
        migrations.DeleteModel(
            name='ReceiptBatch',
        ),
    ]
