# Generated by Django 4.1.1 on 2022-09-16 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("afip", "0022_alter_receiptvalidation_caea"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="caea",
            field=models.ForeignKey(
                blank=True,
                help_text="CAEA in case that the receipt must contain it",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipts",
                to="afip.caea",
            ),
        ),
    ]
