# Generated by Django 4.1.1 on 2022-09-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afip", "0024_informedcaeas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informedcaeas",
            name="processed_date",
            field=models.DateField(verbose_name="processed date"),
        ),
    ]
