# Generated by Django 4.1.1 on 2022-09-22 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("afip", "0011_receiptentry_discount_and_more"),
        ("afip", "0025_alter_informedcaeas_processed_date"),
    ]

    operations = []
