# Generated by Django 4.0.8 on 2022-10-15 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afip', '0027_alter_caea_generated_alter_caea_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ('issued_date', 'point_of_sales_id', 'receipt_number', 'pk'), 'verbose_name': 'receipt', 'verbose_name_plural': 'receipts'},
        ),
    ]
