# Generated by Django 4.1.1 on 2022-10-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afip', '0028_alter_receipt_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='generated',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Time when the receipt was created'),
        ),
    ]
