# Generated by Django 4.0.8 on 2022-10-17 22:35

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('afip', '0030_remove_caea_final_date_inform_caea_report_deadline'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='caea',
            managers=[
                ('actives_caea', django.db.models.manager.Manager()),
            ],
        ),
    ]
