# Generated by Django 4.0.8 on 2022-10-17 22:35

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("afip", "0030_remove_caea_final_date_inform_caea_report_deadline"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="caea",
            managers=[
                ("actives_caea", django.db.models.manager.Manager()),
            ],
        ),
    ]
