# Generated by Django 4.1.1 on 2022-10-17 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afip', '0031_alter_caea_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='caea',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='caea',
            name='active',
        ),
    ]
