# Generated by Django 4.0.8 on 2022-10-18 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("afip", "0032_alter_caea_managers_remove_caea_active"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CaeaCounter",
        ),
    ]
