# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afip', '0032_receiptpdf__client_vat__notnull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptpdf',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='The actual file which contains the PDF data.', null=True, upload_to='receipts', verbose_name='pdf file'),
        ),
    ]
