# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afip', '0034_vat_condition_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptentry',
            name='vat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_entries', to='afip.VatType', verbose_name='vat'),
        ),
    ]
